### ISSUE TITLE
Fix nav style and behaviour 

### ISSUE THREAD

**Issue by abadfederico** [butterproject/butter-style-guide#1]
http://imgur.com/C4jBjFX

- [x] - Text transform uppercase
- [x] - Fix color
- [x] - the line has to start and end with the text not bigger
- [x] - The :hover line has to be white with transparency
- [x] -  Fix hover style

**Comment by abadfederico** [comment]
I can't solve the 3 problem :(

**Comment by btzr-io** [comment]
[img](https://cloud.githubusercontent.com/assets/14793624/21295738/dcf21f78-c518-11e6-953f-2ea2c63ae13c.JPG)
^^ like this??

**Comment by abadfederico** [comment]
@btzr-io yes! a little more centered but THAT <3

**Comment by btzr-io** [comment]
only the first nav is working :(

**Comment by btzr-io** [comment]
fixed??:  https://buttercomponents.github.io/butter-style-guide
